#
# Travis CI config file
#

language: python

python:
  - "3.4"
  - "3.6"


# install dependencies
before_install:
  - 'git clone https://github.com/phfaist/pylatexenc.git --depth=0'
  - '(cd pylatexenc && python setup.py sdist && python -m pip dist/pylatexenc-*.tar.gz)'

# command to run tests
script:
  - PYTHONPATH=. pytest

